// Code generated by "stringer -type=Operation"; DO NOT EDIT.

package AST

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Asmt-0]
	_ = x[LShift-1]
	_ = x[RShift-2]
	_ = x[Add-3]
	_ = x[Sub-4]
	_ = x[Multi-5]
	_ = x[Div-6]
	_ = x[Bracket-7]
	_ = x[Equals-8]
}

const _Operation_name = "AsmtLShiftRShiftAddSubMultiDivBracketEquals"

var _Operation_index = [...]uint8{0, 4, 10, 16, 19, 22, 27, 30, 37, 43}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
