// Code generated by "stringer -type=SignalType"; DO NOT EDIT.

package AST

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Wire-0]
	_ = x[Reg-1]
}

const _SignalType_name = "WireReg"

var _SignalType_index = [...]uint8{0, 4, 7}

func (i SignalType) String() string {
	if i < 0 || i >= SignalType(len(_SignalType_index)-1) {
		return "SignalType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SignalType_name[_SignalType_index[i]:_SignalType_index[i+1]]
}
